[package]
name = "cli-cal"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
chrono-tz = "0.10.4"
clap = {version = "4.5.51", features = ["derive"]}
dateparser = "0.2.1"
regex = "1.12.2"
